id: 2b1b845c-db63-439b-808e-4ec0ebaa1f01
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: TestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: baa05990-4a1a-4269-8a2a-9b4101bdbac8
    type: start
    task:
      id: baa05990-4a1a-4269-8a2a-9b4101bdbac8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 3a24c2b4-4027-4ddb-8010-3f028b64a8a4
    type: regular
    task:
      id: 3a24c2b4-4027-4ddb-8010-3f028b64a8a4
      version: -1
      name: Print Test
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      value:
        simple: Test!
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: abfba620-260b-4c38-847e-9808e906fe16
    type: title
    task:
      id: abfba620-260b-4c38-847e-9808e906fe16
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 375,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
